### ISSUE TITLE
Dependency not on gradle?

### ISSUE THREAD

**Issue by behelit** [sensorberg-dev/permission-bitte#1]
`implementation 'com.sensorberg.libs:permission-bitte:1.0.0'`

results in:

Failed to resolve: com.sensorberg.libs:permission-bitte:1.0.0

**Comment by budius** [comment]
hey @behelit , thanks for the interest in the lib.

At the top of the readme there's "latest version" badge. It's 0.2.2
https://bintray.com/sensorberg/maven/permission-bitte/0.2.2

The lib is stable and I'm fully using in production app, I guess I should move it to 1.0 soon anyway.
